services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ghgcope-be_default
    labels:
      - "coolify.expose=true"
      - "coolify.name=ghgcope-fe"
      - "coolify.port=80"
    ports:
      - "3000:80"

networks:
  ghgcope-be_default:
    external: true
    name: ghgcope-be_default
